
@api=http://localhost:3000/Doctores
@registry=http://localhost:3000/firstRegistry

@prueba=http://localhost:3000/userprueba

GET {{prueba}}

###

GET {{api}}


###
POST {{api}}
Content-Type: application/json

{
    "correo": "svfgh@gmail.com",
    "username": "fdg",
    "contraseña" : "hg"
}


###
GET {{api}}/1

###
DELETE {{api}}/6

###
GET {{api}}/count


###
PUT {{api}}/1002
Content-Type: application/json

{
    "correo": "simituneado@gmail.com",
    "username": "saaa",
    "contraseña" : "similon"
}

###
POST {{registry}}
Content-Type: application/json

{
  "username": "ejemplo2",
  "password": "ejempl2",
  "name": "sdsd",
  "email": "ssvcxvf@correo.com",
  "father": "vc",
  "mother": "vfv",
  "cellphone": "celvfvflphone",
  "age": 30,
  "weight": 70,
  "height": 175,
  "DrID": 1
}
